dist: trusty
language: tex
sudo: false
python: 
  -"3.7"

install:
  - pip install --user Pygments

addons:
    apt: 
        packages:
          - texlive
          - texlive-lang-german
          - texlive-doc-de
          - texlive-latex-extra 
script:
  - pdflatex -interaction=nonstopmode -halt-on-error -shell-escape *.tex

deploy:
  provider: releases
  api_key: $GIT_AUTH
  file: "reference-card.pdf"
  skip_cleanup: true
  on:
    tags: true