dist: trusty
language: tex
sudo: false
python: 
  -"3.7"

install:
  - pip install --user Pygments
  - curl https://raw.githubusercontent.com/gvacaliuc/travis-ci-latex-pdf/master/texlive_install.sh > /tmp/texlive_install.sh
  - source /tmp/texlive_install.sh
  - tlmgr install minted lipsum upquote lineno ifplatform xstring framed tcolorbox environ trimspaces fvextra l3kernel

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
- pdflatex -interaction=nonstopmode -halt-on-error -shell-escape *.tex

deploy:
  provider: releases
  api_key: $GIT_AUTH
  file: "STAT_Python_Referenzkarte.pdf"
  skip_cleanup: true
  on:
    tags: true