dist: trusty
language: tex
sudo: false
python: 
  -"3.7"

install:
  - pip install --user Pygments

addons:
    apt: 
        packages:
          - texlive-full
script:
  - pdflatex -interaction=nonstopmode -halt-on-error -shell-escape *.tex

deploy:
  provider: releases
  api_key: $GIT_AUTH
  file: "STAT_Python_Referenzkarte.pdf"
  skip_cleanup: true
  on:
    tags: true