dist: trusty
language: tex
sudo: false

addons:
    apt: 
        packages:
          - texlive-full
script:
  - pdflatex -interaction=nonstopmode -halt-on-error -shell-escape *.tex

deploy:
  provider: releases
  api_key: $GIT_AUTH
  file: "reference-card.pdf"
skip_cleanup: true